import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main textbook sidebar with four main modules
  textbookSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS2',
      items: [{type: 'autogenerated', dirName: 'module1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      items: [{type: 'autogenerated', dirName: 'module3-ai-robot-brain'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA (Vision-Language-Action)',
      items: [{type: 'autogenerated', dirName: 'module4-vla'}],
    },
  ],
};

export default sidebars;
